version: '3.1'
services:
  library:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8070:8069"
    tty: true # crucial for addons
    command: -- --dev=reload # crucial for addons
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always # (optional) run as a service
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always
volumes:
  odoo-web-data:
  # odoo-db-data: